apiVersion: v1
kind: Service
metadata:
  name: netology-task-2
spec:
  ports:
  - name: nginx
    port: 9001
    targetPort: 80
  - name: multitool
    port: 9002
    targetPort: 8080
  type: NodePort
  selector:
    app: task-1